# Generated by Django 5.2.1 on 2025-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewlog',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
