# Generated by Django 5.2.1 on 2025-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pageviewlog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewlog',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='pageviewlog',
            unique_together={('project', 'ip_address')},
        ),
    ]
