# Generated by Django 5.2.1 on 2025-06-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_skill_percentage_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_hub',
            field=models.URLField(blank=True, null=True),
        ),
    ]
