# Generated by Django 5.2.1 on 2025-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_git_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='Hech qanday malumot mavjud emas.'),
        ),
    ]
