# Generated by Django 5.2.1 on 2025-06-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_project_cover_image_projectcoverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcoverimage',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='main.blogpost'),
        ),
        migrations.AlterField(
            model_name='projectcoverimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='main.project'),
        ),
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
